### ISSUE TITLE
Failed in WxBot getInit

### ISSUE THREAD

**Issue by xzonepiece** [KasperDeng/Hubot-WeChat#15]
[Wed Jul 20 2016 12:44:03 GMT+0800 (中国标准时间)] INFO Construct Robot
[Wed Jul 20 2016 12:44:03 GMT+0800 (中国标准时间)] INFO WxHubot Staring Running
[Wed Jul 20 2016 12:44:04 GMT+0800 (中国标准时间)] ERROR status: 200 
header: {"connection":"keep-alive","x-wx-fj":"001,018,0000001024","x-wx-st":"2","content-type":"text/plain","content-length":"653"}
 body: {"BaseResponse":{"Ret":1100,"ErrMsg":""},"Count":0,"ContactList":[],"SyncKey":{"Count":0,"List":[]},"User":{"Uin":0,"UserName":"","NickName":"","HeadImgUrl":"","RemarkName":"","PYInitial":"","PYQuanPin":"","RemarkPYInitial":"","RemarkPYQuanPin":"","HideInputBarFlag":0,"StarFriend":0,"Sex":0,"Signature":"","AppAccountFlag":0,"VerifyFlag":0,"ContactFlag":0,"WebWxPluginSwitch":0,"HeadImgFlag":0,"SnsFlag":0},"ChatSet":"","SKey":"","ClientVersion":0,"SystemTime":0,"GrayScale":0,"InviteStartCount":0,"MPSubscribeMsgCount":0,"MPSubscribeMsgList":[],"ClickReportInterval":0}

Error: Failed in WxBot getInit

**Comment by mingjin** [comment]
@xzonepiece  从你的header和body来看，你没有配置正确Uin、Sid等这些参数。

你需要先用浏览器的调试模式，通过手机微信客户端扫描二维码登录。这样，你就能够看到cookie、Uin、Sid、Skey、DeviceId这些参数。

接下来，把这些参数填入node_modules/hubot-weixin下的config.yaml，因为src/config.coffee程序里面写的是读这个路径的配置文件。

注意，需要确保你的微信帐号上至少有一个聊天群，否则src/wxbot.coffee在updateGroupMemberList时会报错。

这些做好之后，你应该就可以正常登录网页微信，通过Hubot的hear、send等接口收发消息了

**Comment by xzonepiece** [comment]
@KasperDeng 还是不行，我是在这个请求https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxinit下找到这些参数的，然后填入了node_modules/hubot-weixin下的 config.yaml中，现在的错误是这样的：
> [Wed Jul 27 2016 18:55:37 GMT+0800 (中国标准时间)] INFO Construct Robot
[Wed Jul 27 2016 18:55:37 GMT+0800 (中国标准时间)] INFO WxHubot Staring Running
Error: Failed in WxBot getInit
  at WxBot.getInit (E:\Cloud\openshift\weixinbot\node_modules\hubot-weixin\src\wxbot.coffee:38:15)
  at WxBotAdapter.run (E:\Cloud\openshift\weixinbot\node_modules\hubot-weixin\src\hubot-wx.coffee:57:12)
  at Robot.run (E:\Cloud\openshift\weixinbot\node_modules\hubot\src\robot.coffee:590:14)
  at Object.<anonymous> (E:\Cloud\openshift\weixinbot\node_modules\hubot\bin\hubot:183:11)
  at Object.<anonymous> (E:\Cloud\openshift\weixinbot\node_modules\hubot\bin\hubot:186:4)
  at Module._compile (module.js:413:34)
  at Object.exports.run (C:\Users\xz\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\coffee-script.js:134:23)
  at compileScript (C:\Users\xz\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\command.js:224:29)
  at compilePath (C:\Users\xz\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\command.js:174:14)
  at Object.exports.run (C:\Users\xz\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\command.js:98:20)
  at Object.<anonymous> (C:\Users\xz\AppData\Roaming\npm\node_modules\coffee-script\bin\coffee:7:41)
  at Module._compile (module.js:413:34)
  at Object.Module._extensions..js (module.js:422:10)
  at Module.load (module.js:357:32)
  at Function.Module._load (module.js:314:12)
  at Function.Module.runMain (module.js:447:10)
  at startup (node.js:141:18)
  at node.js:933:3

**Comment by KasperDeng** [comment]
确认你登录的微信号是在`wx.qq.com`还是`wx2.qq.com`. 同样要配置在config.yaml的`baseUrl`和`baseUploadUrl`。

**Comment by xzonepiece** [comment]
@KasperDeng 原来是这样了，谢了

**Comment by kakadeli** [comment]
[Wed Nov 30 2016 13:21:21 GMT+0800 (CST)] INFO Construct Robot
[Wed Nov 30 2016 13:21:21 GMT+0800 (CST)] INFO WxHubot Staring Running
[Wed Nov 30 2016 13:21:21 GMT+0800 (CST)] ERROR Error: The protocol "null" is not supported, cannot load "wx.qq.com/webwxinit"
  at doRequest (/Users/xxx/myhubot/node_modules/sync-request/index.js:31:11)
  at Object.http_post_sync [as post_sync] (/Users/xxx/myhubot/node_modules/hubot-weixin/src/httpclient.coffee:118:5, <js>:147:13)
  at Object.getInit (/Users/xxx/myhubot/node_modules/hubot-weixin/src/wxApi.coffee:79:11, <js>:122:20)
  at WxBot.getInit (/Users/xxx/myhubot/node_modules/hubot-weixin/src/wxbot.coffee:29:5, <js>:46:27)
  at WxBotAdapter.run (/Users/xxx/myhubot/node_modules/hubot-weixin/src/hubot-wx.coffee:57:5, <js>:87:18)
  at Robot.run (/Users/xxx/myhubot/node_modules/hubot/src/robot.coffee:590:5, <js>:464:27)
  at Object.<anonymous> (/Users/xxx/myhubot/node_modules/hubot/bin/hubot:168:8, <js>:182:11)
  at Object.<anonymous> (/Users/xxx/myhubot/node_modules/hubot/bin/hubot:5:1, <js>:185:4)
  at Module._compile (module.js:571:32)
  at Object.exports.run (/Users/xxx/myhubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:103:25)
  at compileScript (/Users/xxx/myhubot/node_modules/coffee-script/lib/coffee-script/command.js:171:29)
  at /Users/xxx/myhubot/node_modules/coffee-script/lib/coffee-script/command.js:143:18
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:415:3)

TypeError: Cannot read property 'getBody' of undefined
  at WxBot._getJsonBody (/Users/xxx/myhubot/node_modules/hubot-weixin/src/wxbot.coffee:274:20, <js>:423:22)
  at WxBot.getInit (/Users/xxx/myhubot/node_modules/hubot-weixin/src/wxbot.coffee:30:16, <js>:47:23)
  at WxBotAdapter.run (/Users/xxx/myhubot/node_modules/hubot-weixin/src/hubot-wx.coffee:57:5, <js>:87:18)
  at Robot.run (/Users/xxx/myhubot/node_modules/hubot/src/robot.coffee:590:5, <js>:464:27)
  at Object.<anonymous> (/Users/xxx/myhubot/node_modules/hubot/bin/hubot:168:8, <js>:182:11)
  at Object.<anonymous> (/Users/xxx/myhubot/node_modules/hubot/bin/hubot:5:1, <js>:185:4)
  at Module._compile (module.js:571:32)
  at Object.exports.run (/Users/xxx/myhubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:103:25)
  at compileScript (/Users/xxx/myhubot/node_modules/coffee-script/lib/coffee-script/command.js:171:29)
  at /Users/xxx/myhubot/node_modules/coffee-script/lib/coffee-script/command.js:143:18
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:415:3)

**Comment by kakadeli** [comment]
还是包这个错为什么，求解

**Comment by kakadeli** [comment]
Error parsing JSON data from external-scripts.json: SyntaxError: Unexpected token 
 in JSON at position 211
