### ISSUE TITLE
同步消息的时候发生异常Error in handling WebSy nc response Error: socket hang up

### ISSUE THREAD

**Issue by gbkhero** [KasperDeng/Hubot-WeChat#18]
是不是最近腾讯又干了什么了，明明前几天还可以用的，现在机器人无法启动，就再同步消息（2S）发生如下错误：
[Wed Aug 31 2016 11:33:52 GMT+0800 (中国标准时间)] ERROR Error in handling WebSy
nc response Error: socket hang up [SyntaxError: Unexpected token E]
之前的初始化步骤都没问题。

**Comment by killuavx** [comment]
出现同样的错误，初始化步骤是好的，后续的同步消息就出现以下错误
<pre>`
[Sat Sep 03 2016 05:42:25 GMT+0000 (UTC)] DEBUG webWxSync running in 2s
[Sat Sep 03 2016 05:42:25 GMT+0000 (UTC)] ERROR Error in handling WebSync response Error: socket hang up SyntaxError: Unexpected token E in JSON at position 0
  at Object.parse (native)
  at WxBot._handleWebSyncCb (/home/hubot/node_modules/hubot-weixin/src/wxbot.coffee:207:9, <js>:320:27)
  at /home/hubot/node_modules/hubot-weixin/src/wxbot.coffee:2:1, <js>:3:61
  at ClientRequest.<anonymous> (/home/hubot/node_modules/hubot-weixin/src/httpclient.coffee:43:5, <js>:52:14)
  at emitOne (events.js:96:13)
  at ClientRequest.emit (events.js:188:7)
  at TLSSocket.socketOnEnd (_http_client.js:344:9)
  at emitNone (events.js:91:20)
  at TLSSocket.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:974:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)`<pre>

**Comment by jasondi** [comment]
所有的get请求都是可以的，post都会出现socket hang up [SyntaxError: Unexpected token E]，你们有什么进展吗

**Comment by Xuanwo** [comment]
我今天刚刚初始化配置了以下，log是这样的：

```
[Mon Sep 12 2016 14:37:29 GMT+0800 (CST)] INFO Construct Robot
[Mon Sep 12 2016 14:37:29 GMT+0800 (CST)] INFO WxHubot Staring Running
[Mon Sep 12 2016 14:37:48 GMT+0800 (CST)] INFO wx robot init done
[Mon Sep 12 2016 14:38:12 GMT+0800 (CST)] ERROR Error in handling WebSync response Error: socket hang up SyntaxError: Unexpected token E in JSON at position 0
  at Object.parse (native)
  at WxBot._handleWebSyncCb (/home/xuanwo/Code/qingchat-hubot/node_modules/hubot-weixin/src/wxbot.coffee:207:9, <js>:320:27)
  at /home/xuanwo/Code/qingchat-hubot/node_modules/hubot-weixin/src/wxbot.coffee:2:1, <js>:3:61
  at ClientRequest.<anonymous> (/home/xuanwo/Code/qingchat-hubot/node_modules/hubot-weixin/src/httpclient.coffee:43:5, <js>:52:14)
  at emitOne (events.js:96:13)
  at ClientRequest.emit (events.js:188:7)
  at TLSSocket.socketOnEnd (_http_client.js:344:9)
  at emitNone (events.js:91:20)
  at TLSSocket.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:934:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by KasperDeng** [comment]
谢谢大家的反馈。最近比较忙，所以没来得及看。周末花了点时间看这个问题，大概是两个问题吧。
   1. syncCheck的api的url有变化
   2. 之前webSync在20160509是改成了异步，为了提高性能，之后一直能work的。但现在好像有问题，会出现大家提到的`socket hang up`。具体原因还不是太清楚，换回同步是能用的。

基于这两个问题，我等下修改下代码，release 1.0.7的版本到npm吧。如果时间足够，我会把webSync的同/异步做成配置项，给以后的异步问题fix留有余地。

**Comment by gztitan** [comment]
@KasperDeng hi,已经修改好了吗，是否NPM install就可以啦

**Comment by jasondi** [comment]
需要在config文件中加入 baseSyncChkUrl: "https://webpush.wx.qq.com/cgi-bin/mmwebwx-bin"
另外wxbot.coffee的137行要缩进两个空格到else分支里面。这样可以跑起来，但sendmessage应该还是有问题

**Comment by gztitan** [comment]
搞定！机器人复活，谢谢@jasondi 和@KasperDeng

**Comment by gztitan** [comment]
复活是复活了，运行半个小时后，发现似乎反应又慢下来，信息好久才出来

**Comment by KasperDeng** [comment]
Fix the code indent mentioned by @jasondi 
暂时来说，我还是保留网页版没退出，因为synCheck还是有点问题的。(暂时要等等，我还没时间搞)
我的机器人跑了12+小时了，没发现反应变慢的问题。
