### ISSUE TITLE
启动失败：Failed in WxBot updateGroupMemberList

### ISSUE THREAD

**Issue by aries-zhang** [KasperDeng/Hubot-WeChat#25]
Error: Failed in WxBot updateGroupMemberList
  at WxBot.updateGroupMemberList (/node_modules/hubot-weixin/src/wxbot.coffee:66:15, <js>:112:13)
  at WxBotAdapter.run (/node_modules/hubot-weixin/src/hubot-wx.coffee:59:5, <js>:89:18)
  at Robot.run (/node_modules/hubot/src/robot.coffee:590:5, <js>:464:27)
  at Object.<anonymous> (/node_modules/hubot/bin/hubot:168:8, <js>:182:11)
  at Object.<anonymous> (/node_modules/hubot/bin/hubot:5:1, <js>:185:4)
  at Module._compile (module.js:570:32)
  at Object.exports.run (/node_modules/coffee-script/lib/coffee-script/coffee-script.js:103:25)
  at compileScript (/node_modules/coffee-script/lib/coffee-script/command.js:171:29)
  at /node_modules/coffee-script/lib/coffee-script/command.js:143:18
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)

**Comment by hanyan007** [comment]
我报的是
[Mon Jan 16 2017 17:33:07 GMT+0800 (CST)] INFO Construct Robot
[Mon Jan 16 2017 17:33:07 GMT+0800 (CST)] INFO WxHubot Staring Running
[Mon Jan 16 2017 17:33:08 GMT+0800 (CST)] ERROR status: 200
 header: {"connection":"keep-alive","content-type":"text/plain","content-length":"653"}
 body: {"BaseResponse":{"Ret":1101,"ErrMsg":""},"Count":0,"ContactList":[],"SyncKey":{"Count":0,"List":[]},"User":{"Uin":0,"UserName":"","NickName":"","HeadImgUrl":"","RemarkName":"","PYInitial":"","PYQuanPin":"","RemarkPYInitial":"","RemarkPYQuanPin":"","HideInputBarFlag":0,"StarFriend":0,"Sex":0,"Signature":"","AppAccountFlag":0,"VerifyFlag":0,"ContactFlag":0,"WebWxPluginSwitch":0,"HeadImgFlag":0,"SnsFlag":0},"ChatSet":"","SKey":"","ClientVersion":0,"SystemTime":0,"GrayScale":0,"InviteStartCount":0,"MPSubscribeMsgCount":0,"MPSubscribeMsgList":[],"ClickReportInterval":0}
 
Error: Failed in WxBot getInit
  at WxBot.getInit (/root/soft/Hubot-WeChat-master/src/wxbot.coffee:38:15, <js>:63:13)
  at WxBotAdapter.run (/root/soft/Hubot-WeChat-master/src/hubot-wx.coffee:57:5, <js>:87:18)
  at Robot.run (/root/soft/myhubot/node_modules/hubot/src/robot.coffee:590:5, <js>:464:27)
  at Object.<anonymous> (/root/soft/myhubot/node_modules/hubot/bin/hubot:168:8, <js>:182:11)
  at Object.<anonymous> (/root/soft/myhubot/node_modules/hubot/bin/hubot:5:1, <js>:185:4)

**Comment by hanyan007** [comment]
@aries-zhang  你的问题我也复现了，解决了吗？

**Comment by awei4home** [comment]
这个解决了么，我也遇到了

**Comment by awei4home** [comment]
Failed in WxBot updateGroupMemberList，这个我的测试中发现，新注册的微信号如果没有群会报这个，你可以在测试微信号建个群就可以了，我这边这样做可以了
