### ISSUE TITLE
Error: failed in WxBot getInit

### ISSUE THREAD

**Issue by ScottShao** [KasperDeng/Hubot-WeChat#27]
I started the hubot with command: bin/hubot -a weixin and got an error as follows:
[Wed Mar 08 2017 08:38:23 GMT-0500 (EST)] INFO Construct Robot
[Wed Mar 08 2017 08:38:23 GMT-0500 (EST)] INFO WxHubot Staring Running
[Wed Mar 08 2017 08:38:32 GMT-0500 (EST)] ERROR status: 200
 header: {"connection":"keep-alive","content-type":"text/plain","content-length":"650"}
 body: {"BaseResponse":{"Ret":1,"ErrMsg":""},"Count":0,"ContactList":[],"SyncKey":{"Count":0,"List":[]},"User":{"Uin":0,"UserName":"","NickName":"","HeadImgUrl":"","RemarkName":"","PYInitial":"","PYQuanPin":"","RemarkPYInitial":"","RemarkPYQuanPin":"","HideInputBarFlag":0,"StarFriend":0,"Sex":0,"Signature":"","AppAccountFlag":0,"VerifyFlag":0,"ContactFlag":0,"WebWxPluginSwitch":0,"HeadImgFlag":0,"SnsFlag":0},"ChatSet":"","SKey":"","ClientVersion":0,"SystemTime":0,"GrayScale":0,"InviteStartCount":0,"MPSubscribeMsgCount":0,"MPSubscribeMsgList":[],"ClickReportInterval":0}

Error: Failed in WxBot getInit
  at WxBot.getInit (/Users/zhaoyangshao/Documents/wechat-hubot/wechat-plugin/src/wxbot.coffee:38:15, <js>:63:13)
  at WxBotAdapter.run (/Users/zhaoyangshao/Documents/wechat-hubot/wechat-plugin/src/hubot-wx.coffee:57:5, <js>:87:18)
  at Robot.run (/Users/zhaoyangshao/Documents/wechat-hubot/node_modules/hubot/src/robot.coffee:590:5, <js>:464:27)
  at Object.<anonymous> (/Users/zhaoyangshao/Documents/wechat-hubot/node_modules/hubot/bin/hubot:168:8, <js>:182:11)
  at Object.<anonymous> (/Users/zhaoyangshao/Documents/wechat-hubot/node_modules/hubot/bin/hubot:5:1, <js>:185:4)
  at Module._compile (module.js:570:32)
  at Object.exports.run (/Users/zhaoyangshao/Documents/wechat-hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:103:25)
  at compileScript (/Users/zhaoyangshao/Documents/wechat-hubot/node_modules/coffee-script/lib/coffee-script/command.js:171:29)
  at /Users/zhaoyangshao/Documents/wechat-hubot/node_modules/coffee-script/lib/coffee-script/command.js:143:18
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)

any idea why? thanks

**Comment by zhangbo1817** [comment]
Do you grab the skey value?

**Comment by CodeDogandCat** [comment]
用你绑定的微信号建一个群,并在里面说一句话,然后在重新启动

**Comment by Sofar777** [comment]
@CodeDogandCat 刚才还正常使用了一下，退出网页版微信这边就不行了。然后就不正常了，5个参数重新填都没有用。
