### ISSUE TITLE
Error: Failed in WxBot getInit

### ISSUE THREAD

**Issue by zhangbo1817** [KasperDeng/Hubot-WeChat#28]
@KasperDeng 检查了一遍配置，发现skey为空，有问题吗？一直起不来~
 bin/hubot -a weixin
[Sat Mar 18 2017 16:16:47 GMT+0800 (CST)] INFO Construct Robot
[Sat Mar 18 2017 16:16:47 GMT+0800 (CST)] INFO WxHubot Staring Running
[Sat Mar 18 2017 16:16:47 GMT+0800 (CST)] ERROR status: 200
 header: {"connection":"keep-alive","content-type":"text/plain","content-length":"653"}
 body: {"BaseResponse":{"Ret":1101,"ErrMsg":""},"Count":0,"ContactList":[],"SyncKey":{"Count":0,"List":[]},"User":{"Uin":0,"UserName":"","NickName":"","HeadImgUrl":"","RemarkName":"","PYInitial":"","PYQuanPin":"","RemarkPYInitial":"","RemarkPYQuanPin":"","HideInputBarFlag":0,"StarFriend":0,"Sex":0,"Signature":"","AppAccountFlag":0,"VerifyFlag":0,"ContactFlag":0,"WebWxPluginSwitch":0,"HeadImgFlag":0,"SnsFlag":0},"ChatSet":"","SKey":"","ClientVersion":0,"SystemTime":0,"GrayScale":0,"InviteStartCount":0,"MPSubscribeMsgCount":0,"MPSubscribeMsgList":[],"ClickReportInterval":0}
 
Error: Failed in WxBot getInit
  at WxBot.getInit (/Users/zhangbo/alibaba/myrobot/node_modules/hubot-weixin/src/wxbot.coffee:38:15, <js>:63:13)
  at WxBotAdapter.run (/Users/zhangbo/alibaba/myrobot/node_modules/hubot-weixin/src/hubot-wx.coffee:57:5, <js>:87:18)
  at Robot.run (/Users/zhangbo/alibaba/myrobot/node_modules/hubot/src/robot.coffee:590:5, <js>:464:27)
  at Object.<anonymous> (/Users/zhangbo/alibaba/myrobot/node_modules/hubot/bin/hubot:168:8, <js>:182:11)
  at Object.<anonymous> (/Users/zhangbo/alibaba/myrobot/node_modules/hubot/bin/hubot:5:1, <js>:185:4)
  at Module._compile (module.js:409:26)
  at Object.exports.run (/Users/zhangbo/alibaba/myrobot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:103:25)
  at compileScript (/Users/zhangbo/alibaba/myrobot/node_modules/coffee-script/lib/coffee-script/command.js:171:29)
  at /Users/zhangbo/alibaba/myrobot/node_modules/coffee-script/lib/coffee-script/command.js:143:18
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

**Comment by KasperDeng** [comment]
skey可以为空，你抓到的skey是什么就填什么到配置里面。我看你的Return Code是`1101`一般是配置问题。你再检查下你用的url是不是对的，尤其是`wx`还是`wx2`。

**Comment by zhangbo1817** [comment]
thanks very much，还是配置的问题，已解决

**Comment by shaowin16** [comment]
您好，我也遇到了同样的问题，我的报错信息如下：
```
[Wed Apr 05 2017 11:06:55 GMT+0800 (CST)] INFO Construct Robot
[Wed Apr 05 2017 11:06:55 GMT+0800 (CST)] INFO WxHubot Staring Running
[Wed Apr 05 2017 11:06:55 GMT+0800 (CST)] ERROR status: 200
 header: {"connection":"keep-alive","content-type":"text/plain","content-length":"650"}
 body: {"BaseResponse":{"Ret":1,"ErrMsg":""},"Count":0,"ContactList":[],"SyncKey":{"Count":0,"List":[]},"User":{"Uin":0,"UserName":"","NickName":"","HeadImgUrl":"","RemarkName":"","PYInitial":"","PYQuanPin":"","RemarkPYInitial":"","RemarkPYQuanPin":"","HideInputBarFlag":0,"StarFriend":0,"Sex":0,"Signature":"","AppAccountFlag":0,"VerifyFlag":0,"ContactFlag":0,"WebWxPluginSwitch":0,"HeadImgFlag":0,"SnsFlag":0},"ChatSet":"","SKey":"","ClientVersion":0,"SystemTime":0,"GrayScale":0,"InviteStartCount":0,"MPSubscribeMsgCount":0,"MPSubscribeMsgList":[],"ClickReportInterval":0}

Error: Failed in WxBot getInit
  at WxBot.getInit (/Users/chenshaowen/workspace/myhubot/node_modules/hubot-weixin/src/wxbot.coffee:38:15, <js>:63:13)
  at WxBotAdapter.run (/Users/chenshaowen/workspace/myhubot/node_modules/hubot-weixin/src/hubot-wx.coffee:57:5, <js>:87:18)
  at Robot.run (/Users/chenshaowen/workspace/myhubot/node_modules/hubot/src/robot.coffee:590:5, <js>:464:27)
  at Object.<anonymous> (/Users/chenshaowen/workspace/myhubot/node_modules/hubot/bin/hubot:168:8, <js>:182:11)
  at Object.<anonymous> (/Users/chenshaowen/workspace/myhubot/node_modules/hubot/bin/hubot:5:1, <js>:185:4)
  at Module._compile (module.js:571:32)
  at Object.exports.run (/Users/chenshaowen/workspace/myhubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:103:25)
  at compileScript (/Users/chenshaowen/workspace/myhubot/node_modules/coffee-script/lib/coffee-script/command.js:171:29)
  at /Users/chenshaowen/workspace/myhubot/node_modules/coffee-script/lib/coffee-script/command.js:143:18
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:437:3)
```
请问是什么问题呢？你们说的配置问题是在哪里配置什么呢？
