### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by fanglei03** [KasperDeng/Hubot-WeChat#39]
> SyntaxError: Unexpected token < in JSON at position 0
  at Object.parse (native)
  at WxBot._getJsonBody (/opt/myhubot/node_modules/hubot-weixin/src/wxbot.coffee:275:12, <js>:424:19)
  at WxBot.getInit (/opt/myhubot/node_modules/hubot-weixin/src/wxbot.coffee:30:16, <js>:47:23)
  at WxBotAdapter.run (/opt/myhubot/node_modules/hubot-weixin/src/hubot-wx.coffee:57:5, <js>:87:18)
  at Robot.run (/opt/myhubot/node_modules/hubot/src/robot.coffee:590:5, <js>:464:27)
  at Object.<anonymous> (/opt/myhubot/node_modules/hubot/bin/hubot:168:8, <js>:182:11)
  at Object.<anonymous> (/opt/myhubot/node_modules/hubot/bin/hubot:5:1, <js>:185:4)
  at Module._compile (module.js:570:32)
  at Object.exports.run (/opt/myhubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:103:25)
  at compileScript (/opt/myhubot/node_modules/coffee-script/lib/coffee-script/command.js:171:29)
  at /opt/myhubot/node_modules/coffee-script/lib/coffee-script/command.js:143:18
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:447:3)

**Comment by wiwengweng** [comment]
你的配置文件是不是写错了。检查一下格式；
