### ISSUE TITLE
启动 Failed in WxBot getInit

### ISSUE THREAD

**Issue by benqethan** [KasperDeng/Hubot-WeChat#42]
按照说明修改了配置：
```
cookie: "wxuin=2166156884; mm_lang=en_US; webwxuvid=9194af00c95b837f9b4f87389f73f5474252def6eeb701043d11049023216e8c8f4a21ecce4e2b83a207663f75ad1c74; MM_WX_NOTIFY_STATE=1; MM_WX_SOUND_STATE=1; refreshTimes=1; wxsid=CZvj52imjY5EJ2cw; webwx_data_ticket=gSe11etFJHhcnzoGZZeapVJT; webwx_auth_ticket=CIsBEP/ewD4agAGJxbJ/0avkJmA/LtrycIcmG90ziTyoZahgJV40Wf14/8qmYC10a08q/WRgyg4sbHK9a1QegHsth+7+FpOm18AubfOZ+u0GC7DvLGhG3Xb+Pv6AcHq+K+l+r9MxdhxBbpOVJEjc9BziCYCewGyNtmFbIsqf/8RxL8RC/gEyWrPkKA==; wxloadtime=1526176040_expired; wxpluginkey=1526166122"

Uin: "2166156884"
Sid: "CZvj52imjY5EJ2cw"
Skey: ""
DeviceID: "e556571604903149"
```
但启动报错，好像是登录有问题：
```
$ bin/hubot -a weixin
[Sat May 12 2018 21:57:35 GMT-0400 (EDT)] INFO Construct Robot
[Sat May 12 2018 21:57:35 GMT-0400 (EDT)] INFO WxHubot Staring Running
[Sat May 12 2018 21:57:36 GMT-0400 (EDT)] ERROR status: 200
 header: {"connection":"keep-alive","content-type":"text/plain","strict-transport-security":"max-age=31536000 ; includeSubDomains","content-length":"653"}
 body: {"BaseResponse":{"Ret":1100,"ErrMsg":""},"Count":0,"ContactList":[],"SyncKey":{"Count":0,"List":[]},"User":{"Uin":0,"UserName":"","NickName":"","HeadImgUrl":"","RemarkName":"","PYInitial":"","PYQuanPin":"","RemarkPYInitial":"","RemarkPYQuanPin":"","HideInputBarFlag":0,"StarFriend":0,"Sex":0,"Signature":"","AppAccountFlag":0,"VerifyFlag":0,"ContactFlag":0,"WebWxPluginSwitch":0,"HeadImgFlag":0,"SnsFlag":0},"ChatSet":"","SKey":"","ClientVersion":0,"SystemTime":0,"GrayScale":0,"InviteStartCount":0,"MPSubscribeMsgCount":0,"MPSubscribeMsgList":[],"ClickReportInterval":0}
 
Error: Failed in WxBot getInit
  at WxBot.getInit (/media/cui/deve/src/Hubot-WeChat/src/wxbot.coffee:38:15, <js>:63:13)
  at WxBotAdapter.run (/media/cui/deve/src/Hubot-WeChat/src/hubot-wx.coffee:57:5, <js>:87:18)
  at Robot.run (/media/cui/deve/src/hubot/src/robot.js:644:18)
  at Object.<anonymous> (/media/cui/deve/src/hubot/bin/hubot.js:112:7)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (/media/cui/deve/src/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/media/cui/deve/src/hubot/bin/hubot:12:1, <js>:2:3)
  at Object.<anonymous> (/media/cui/deve/src/hubot/bin/hubot:12:1, <js>:4:4)
  at Module._compile (module.js:570:32)
  at Object.exports.run (/media/cui/deve/src/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:103:25)
  at compileScript (/media/cui/deve/src/hubot/node_modules/coffee-script/lib/coffee-script/command.js:171:29)
  at /media/cui/deve/src/hubot/node_modules/coffee-script/lib/coffee-script/command.js:143:18
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)
```

**Comment by huyifanstar** [comment]
我的安装完 WxBot以后 提示没有WxBot
https://github.com/liuwons/wxBot 参考这个来安装的
但是启动的时候没提示没有wxbot 模块
这应该怎么办？

**Comment by shilei812** [comment]
baseUrl: "https://wx2.qq.com/cgi-bin/mmwebwx-bin" #wx/wx2

改成

baseUrl: "https://wx.qq.com/cgi-bin/mmwebwx-bin" #wx/wx2

试试看
