### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by cliuxinxin** [KasperDeng/Hubot-WeChat#5]
[root@localhost myhubot]# bin/hubot -a weixin
[Thu May 05 2016 22:08:17 GMT-0400 (EDT)] INFO Construct Robot
[Thu May 05 2016 22:08:17 GMT-0400 (EDT)] INFO WxHubot Staring Running
[Thu May 05 2016 22:08:26 GMT-0400 (EDT)] INFO wx robot init done
Error: watch  ENOENT
  at exports._errnoException (util.js:949:11)
  at FSWatcher.start (fs.js:1423:19)
  at Object.fs.watch (fs.js:1450:11)
  at WxBot.sendLatestImage (/root/myhubot/node_modules/hubot-weixin/src/wxbot.co                                                                                                                     ffee:171:5, <js>:283:17)
  at WxBotAdapter.run (/root/myhubot/node_modules/hubot-weixin/src/hubot-wx.coff                                                                                                                     ee:60:5, <js>:93:18)
  at Robot.run (/root/myhubot/node_modules/hubot/src/robot.coffee:590:5, <js>:46                                                                                                                     4:27)
  at Object.<anonymous> (/root/myhubot/node_modules/hubot/bin/hubot:135:8, <js>:                                                                                                                     149:11)
  at Object.<anonymous> (/root/myhubot/node_modules/hubot/bin/hubot:5:1, <js>:15                                                                                                                     2:4)
  at Module._compile (module.js:541:32)
  at Object.exports.run (/root/myhubot/node_modules/coffee-script/lib/coffee-scr                                                                                                                     ipt/coffee-script.js:103:25)
  at compileScript (/root/myhubot/node_modules/coffee-script/lib/coffee-script/c                                                                                                                     ommand.js:171:29)
  at /root/myhubot/node_modules/coffee-script/lib/coffee-script/command.js:143:1                                                                                                                     8
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)

反复安装也没用，日志也看不到

**Comment by cliuxinxin** [comment]
找到原因了，原来没有图片的目录，在config.yml里面设置好就能启动了

**Comment by KasperDeng** [comment]
这个我应该改过了的，现在主代码里面没有检查图片目录的吧。你是通过npm安装的还是通过代码安装的？npm上已经是1.0.4的版本了，fix了些许问题的。

**Comment by cliuxinxin** [comment]
直接在package.json，里面添加hubot-weixin 1.0.4,然后npm install，现在想想，应该是不要写版本号，估计就好了。

**Comment by KasperDeng** [comment]
嗯。你最好检查下是否有新版本。
版本在`package.json`里面有很多的表达式的，可以参考[The semantic versioner for npm](https://github.com/npm/node-semver)
现在的版本可以在下面的链接查看的，两个是一样的，一般会同步。国内的话，访问taobao npm会快点。
- [hubot-weixin npmjs](https://www.npmjs.com/package/hubot-weixin)
- [hubot-weixin taobao npm](https://npm.taobao.org/package/hubot-weixin)

**Comment by cliuxinxin** [comment]
非常详细，非常感谢，这个问题没啥问题了，现在就是看看如何让脚本更有意思。
