### ISSUE TITLE
Error: Failed in WxBot getInit

### ISSUE THREAD

**Issue by gztitan** [KasperDeng/Hubot-WeChat#8]
一运行的./bin/hubot -a weixin，就出现错误
[Fri Jun 03 2016 09:58:51 GMT+0800 (CST)] INFO WxHubot Staring Running
Error: Failed in WxBot getInit
  at WxBot.getInit (/myprojects/myhubot/titanbot/node_modules/hubot-weixin/src/wxbot.coffee:38:15, <js>:63:13)
  at WxBotAdapter.run (/myprojects/myhubot/titanbot/node_modules/hubot-weixin/src/hubot-wx.coffee:57:5, <js>:87:18)
  at Robot.run (/myprojects/myhubot/titanbot/node_modules/hubot/src/robot.coffee:590:5, <js>:464:27)
  at Object.<anonymous> (/myprojects/myhubot/titanbot/node_modules/hubot/bin/hubot:168:8, <js>:182:11)
  at Object.<anonymous> (/myprojects/myhubot/titanbot/node_modules/hubot/bin/hubot:5:1, <js>:185:4)
  at Module._compile (module.js:435:26)
  at Object.exports.run (/myprojects/myhubot/titanbot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:103:25)
  at compileScript (/myprojects/myhubot/titanbot/node_modules/coffee-script/lib/coffee-script/command.js:171:29)
  at /myprojects/myhubot/titanbot/node_modules/coffee-script/lib/coffee-script/command.js:143:18
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

**Comment by gztitan** [comment]
不知道是否由于这步错：
“从webwxinit api 抓取以下数据
header
cookie
BaseRequest
Uin
Sid
Skey
DeviceId
抓取到的数据填到config.yaml对应的配置项。”

**Comment by gztitan** [comment]
搞定了，真的是webwxinit api 抓取数据的问题

**Comment by Sofar777** [comment]
@gztitan 你是怎么抓取出来的呢？我刚还能正常使用现在就不能使用了
